#!/bin/bash
[ -z $JEKYLL_SITE_ROOT ] && JEKYLL_SITE_ROOT="$HOME/Documentos/blog"
[ -z $EDITOR ] && EDITOR=nvim
[ -z $site_destination ] &&	site_destination="$HOME/Documentos/Git/Personal/rodrigo-barros.github.io/blog"

show_help(){
cat << EOL
jekyll-helper post opções:

-e                  edita esse script

--new               cria um novo post e abre no seu editor favorito
--build             gera os arquivos do site final
--serve             inicia o servidor em localhost para testar seu site
--draft             inicia a edição do post como rascunho
--manage            gerencia os seus post permitindo alterar o estado entre rascunho e publico e publicar
					as alterações no seu blog
--publish           publica as alterações no blog
EOL

exit 0
}

friendly_post_name(){
	data=$(date +"%Y-%m-%d-")
	post_title="$data$1.markdown"
	hifen="s/\s/-/g"
	lowercase="s/(\w|\d)/\l\1/g"
	echo $post_title | sed -r $hifen | sed -r $lowercase
}

post(){
post_type="$1"

case $post_type in
	new)
		working_dir="_posts";;
	draft)
		working_dir="_drafts";;
	*)
		echo "Esse função só aceita new ou draft como argumento"; exit 1 ;;
esac

# CREATE $JEKYLL_SITE_ROOT IF NOT EXISTS
[ ! -e $JEKYLL_SITE_ROOT ] && mkdir $JEKYLL_SITE_ROOT/$working_dir

printf "Titulo:"
read titulo

printf "Categorias:"
read categorias

data=$(date +"%Y-%m-%d %H:%M:%S")
file=$(friendly_post_name "$titulo")

cat << EOF > $JEKYLL_SITE_ROOT/$working_dir/$file
---
layout: post
title:  "$titulo"
date:   $data -0300
categories: $categorias
---
EOF

$EDITOR $JEKYLL_SITE_ROOT/$working_dir/$file
manage
}

publish(){
	cd $JEKYLL_SITE_ROOT
	JEKYLL_ENV=production jekyll build -d $site_destination
	cd $site_destination
	git add $site_destination
	git status
	printf "\nPublicar as alterações acima? (s/n)"
	read response
	if [ "$response" = "s" ];then
		git commit
		git push origin master
	else
		printf "\nSaindo sem fazer nenhuma alteração"
	fi
}

manage(){
# cat << EOL 
# Opções:

# Gerenciar Posts(p)
# Gerenciar Rascunhos(r)
# Sair (q)

# EOL

# read -sn 1 option
local options=""
options+="Gerenciar Posts(p)\n"
options+="Gerenciar Rascunhos(r)\n"
options+="Sair (q)\n"
options+="Novo Post(n)\n"
options+="Novo Rascunho(d)\n"
options+="Publicar alterações para o site(P)"

# Two entry modes ares avaible by hiting enter and by use the keyboard shortcut
choose_method=$(echo -e $options | fzf --expect=h,p,r,q,n,d,P)
length=$( expr $(printf $choose_method | cut -d " " -f1| wc -m) - 1 )

if [ $length -gt 1 ]; then
	option=$(echo $choose_method | sed -r "s/(.+\((\w)\))/\2/" )
else
	option=$(echo $choose_method | cut -d " " -f1)
fi

case $option in 
	n)
		post "new";;
	d)
		post "draft";;
	r)
		do_action "_drafts";;
	p)
		do_action "_posts";;
	P)
		publish;;
	q)
		exit 0;;
	*)
		echo -e "\nOpção incorreta." ; manage;;
esac
}

do_action(){
target="$1"
posts=$(ls $JEKYLL_SITE_ROOT/$target | fzf --multi --expect=q,ctrl-h)

action=$(echo -e "$posts" | cut -d " " -f1)

case $action in
	q)
		exit 0;;
	ctrl-h)
		manage;;
esac

local actions=""
actions+="Editar(e)\n"
actions+="Mover(m)\n"
actions+="Excluir(d)\n"
actions+="Página inicial(h)\n"
actions+="Sair(q)\n"

action=$(echo -e $actions | fzf --expect=e,m,d,h,q | head -n 1)

case $action in
	d)
		delete $target "$posts";;
	e)
		edit $target "$posts";;
	h)
		manage;;
	m)
		move_from $target "$posts";;
	q)
		exit 0;;
	*)
		echo -e "Opção incorreta"; manage;;
esac

}

delete(){
	target="$1"
	posts="$2"
	for post in $posts;do
		rm -i $JEKYLL_SITE_ROOT/$target/$post
	done
	manage
}

edit(){
	target="$1"
	posts="$2"
	files_list=""
	for post in $posts;do
		files_list+="$JEKYLL_SITE_ROOT/$target/$post "
	done

	$EDITOR $files_list
	manage
}

move_from(){
	from="$1"
	posts="$2"

	case $from in
		_drafts)
			to="_posts";;
		_posts)
			to="_drafts";;
		*)
			echo -e "\nOpção incorreta"; manage;;
	esac

	#posts=$(ls $JEKYLL_SITE_ROOT/$from | fzf --multi)
	for i in $posts;do
		#echo -e "\n mv $JEKYLL_SITE_ROOT/$from/$i $JEKYLL_SITE_ROOT/$to/$i"
		echo -e "\n\nmoving $from/$i to $to"
		mv $JEKYLL_SITE_ROOT/$from/$i $JEKYLL_SITE_ROOT/$to/$i 
	done
	sleep .5
	manage
}

for arg in "$@"; do
	case $arg in
		--new)
			post "new";;
		--draft)
			post "draft";;
		--manage)
			manage;;
		--publish)
			publish;;
		-e)
			exec $EDITOR $0;;
		*)
			show_help;;
	esac
done
