#!/bin/bash
set -e
. $HOME/.nix-profile/etc/profile.d/profile.sh
REMIND_FILE="$HOME/.config/nixpkgs/packages/remind/tarefas"
function main(){
    local options=()
    append_menu options "Tarefas"
    append_menu options "Sair"
    # local option=$(get_option options)
    choose=$(get_option options "Rofi"| cut -d " " -f1)

    case $choose in
        1)
            taskmenu;;
        2)
            exit 0;;
    esac
}

function has_id(){
    option=$1
    id=$(echo $option | awk '{print $1}')
    echo $id | grep -E "[0-9]+" 1> /dev/null
}

function get_option(){
    array=$1[@]
    [ -z "$2" ] && prompt='dmenu' || prompt=$2
    [ -z "$3" ] && extraArgs=() || extraArgs="$3"

    array_name=$array
    array_values="\${$array[@]}"
    array_lenght=$(eval echo "\${#$1[@]}")

    local use_index=true
    local index=0

    for option in "${!array}";do
        has_id "$option" && use_index=false 
        local description=$(echo $option | cut -d ' ' -f1-)

        let index+=1
        if [ "$use_index" = "false" ];then
            id=$(echo $option|awk '{print $1}')
            description=$(echo $description | sed -r "s/\s?$id\s//g")
        else
            id=$index
        fi


        if [ $index -eq $array_lenght ];then
            values+="$id $description"
        else
            values+="$id $description\|"
        fi
    done

    ROFI_COMMAND=("echo" "-e" "$values" "|" "rofi" "-dmenu" "-p" "$prompt" "-sep" "\|")

    # extra args
    ROFI_COMMAND+=($extraArgs)

    eval ${ROFI_COMMAND[@]}
}

function get_text_input(){
    prompt=$@
    [ -z "$prompt" ] && prompt=rofi
    rofi -dmenu -p "$prompt"
}

function taskmenu(){
    local options=()
    append_menu options "Adicionar Nova tarefa/Lembrete"
    append_menu options "Listar Tarefas"
    append_menu options "Voltar"
    choose=$(get_option options "Tarefas" | cut -d " " -f1)

    case $choose in
        1)
            taskadd;;
        2)
            tasklist;;
        3) 
            main;;
    esac
}

function taskadd(){
    #local task=$(rofi -dmenu -p "Nova Tarefa")
    local task=$(get_text_input "Nova Tarefa")
    /home/rodrigo/.config/nixpkgs/scripts/taskremind $task
    systemctl --user restart remind-notifier
    notify-send "Remind Warrior:" "Tarefa adicionada $?"
    taskmenu
}

function tasklist(){
    local options=()
    local tasks_active=$(task export active | jq '.[] | .id')
    local tasks=$(task list rc.report.list.columns=id,description.count rc.report.list.labels=ID,Description | sed 1d | sed '$d' | sed 2d )
    [ -z $task_active ] && task_active=-1


    local index=0
    IFS=$'\n'
    for task in $tasks;do
        if [ $index -eq 0 ];then
            mesg="$task"
            let index+=1
            continue
        fi
        local taskid=$(expr $task | awk '{print $1}')
        task_name=$(echo $task | cut -d " " -f2- | sed -r "s/[0-9]+\s+//g")
        
        local focused_task_active
        # current active task
        if [ $(echo $tasks_active | grep $taskid -w ) ];then
            task_name+=" [A]" 
            
            if [ $(echo $focused_task_active | wc -w) -eq 0 ];then
                focused_task_active+=$(( $index - 1 ))
            else
                focused_task_active+=",$(( $index - 1 ))"
            fi
        fi
        append_menu options "$taskid $task_name"
        let index+=1
    done


    tasklen=${#options[@]}
    
    # add menu when there no tasks
    if [ $tasklen -eq 0 ];then
        mesg="Você não possui tarefas"
        append_menu options "Voltar"
    fi

    extraArgs="-mesg '$mesg' -a $focused_task_active"
    #read user input
    choose=$(get_option options "Tarefas" $extraArgs)

    [ $tasklen -eq 0 ] && taskmenu 
    #cat $REMIND_FILE
    taskview "$choose"
}

function taskview(){
    local taskdescription="$1"
    local taskid=$(echo $1 | awk '{print $1}')
    local taskname=$(echo $1 | cut -d " " -f2- )
    local options=()
    append_menu options "Iniciar Tarefa"
    append_menu options "Pausar Tarefa"
    append_menu options "Concluir Tarefa"
    append_menu options "Excluir Tarefa"
    append_menu options "Voltar"
    choose=$(get_option options "Tarefa $taskid" "tarefa: $task_name" | cut -d " " -f1)
    case $choose in
        1)
            taskstart $taskid;;
        2)
            taskstop $taskid;;
        3)
            taskdone $taskid "$taskname";;
        4)
            taskdel $taskid "$taskname";;
        5)
            taskmenu;;
    esac
}


function taskdone(){
    local taskid=$1
    local taskname=$2
    sed "/$taskname/d" $REMIND_FILE -i
    task done $taskid
    tasklist
}

function taskdel(){
    local taskid=$1
    local taskname=$2
    local task_options="rc.confirmation=false"
    sed "/$taskname/d" $REMIND_FILE -i 
    task delete $taskid $task_options
    tasklist
}

function taskstart(){
    local taskid=$1
    task start $taskid
    tasklist
}

function taskstop(){
    local taskid=$1
    task stop $taskid
    tasklist
}

function eval_echo(){
    cmd=$@
    eval echo "$cmd"
}

function append_menu(){
    array=$1
    value=$2
    # echo $value
    local nl=$'\n'
    array_lenght=$(eval_echo "\${#$array[@]}")
    # echo $array[$array_lenght]=\"$value\\n\"
    eval $array[$array_lenght]=\"$value\"
}

main
