#!/bin/bash
taskwarrior="task add "
remind="REM "

desc=""
tags=""
project=""
due=""
#task="corrigir +bug em @blueweb &21 14:00+10 +1w"
#task="corrigir +bug em @blueweb &21 14:00+10 08-07-22+1d"
task="arrumar problema de transferencia de ligações +bug +frontend +backend @blueweb &23 14:00 1m"

#printf "Informe os detalhes da tarefa:"
#read task

check_regex(){
  word=$1
	pattern=$2
  echo $word | grep -E "$pattern"
}

replace(){
 string=$1
 search_string=$2
 replace_by=$3
 echo $string | sed "s/$search_string/$replace_by/"
}

for word in $task; do
	# Palavra normal
   if [ $(check_regex "$word" "^[a-zA-Z]") ];then
	   taskwarrior+="$word "
		 remind+="$word "

		 desc+="$word "
	 
	 # Assunto/Categoria
   elif [ $(check_regex "$word" "^\+[a-zA-Z]") ];then
	   taskwarrior+="$word "
	 	 current_word=$(replace "$word" "+" "")
		 #remind+="$current_word "
		 tags+="$word "

   # Projeto
   elif [ $(check_regex "$word" "^@") ];then
	 	 current_word=$(replace "$word" "@" "")
	   taskwarrior+="project:$current_word "
		 remind+="$current_word "

		 project="project:$current_word"

	 # Depends
   elif [ $(check_regex "$word" "^&") ];then
		current_word=$(replace "$word" "&" "")
		taskwarrior+="depends:$current_word "

		depends+="depends:$current_word "

	 # Hora
 	 elif [ $(check_regex "$word" "([0-9]\+)?[0-9]{2}:[0-9]{2}") ];then
	  hour=$(echo $word | sed -r "s/([0-9]{2}\+)?([0-9]{2}:[0-9]{2})/\2/")
		notification_before_time=$(echo $word | sed -r "s/([0-9]{2}\+)([0-9]{2}:[0-9]{2})/\1/")
    [ $notification_before_time = $hour ] && notification_before_time=""
   
   # Dias a frente
 	 elif [ $(check_regex "$word" "^(\+[0-9])?([0-9])+d(ays)?$") ];then
	  days=$(echo $word | sed -r "s/(d|\+)//g")
	  due_date=$(date -d "$days days " +"%Y-%m-%d")
		due="due:$due_date"
		# TODO: fazer os dias de notificação irem para o remind
    #remind+="$current_word "

   # Semanas a frente
 elif [ $(check_regex "$word" "^(\+[0-9])?[0-9]{1,}w(eeks)?$") ];then
	  weeks=$(echo $word | sed -r "s/(w|\+)//g")
	  due_date=$(date -d "$weeks weeks " +"%Y-%m-%d")
		due="due:$due_date"
		# TODO: fazer os dias de notificação irem para o remind
		taskwarrior+="due:$word"

   # Meses a frente
 elif [ $(check_regex "$word" "^(\+[0-9dwm])?[0-9]{1,}m(onths)?$") ];then
	  months=$(echo $word | sed -r "s/(m|\+)//g")
	  due_date=$(date -d "$months months " +"%Y-%m-%d")
		due="due:$due_date"
		# TODO: fazer os dias de notificação irem para o remind
		taskwarrior+="due:$word"
    #remind+="$current_word "

	 # Dia especifico para a tarefa/lembrete
	 #elif [ $(check_regex "$current_word" "^[0-9]{2}-[0-9]{2}-[0-9]{2,4}\+?([0-9a-z]{2})?") ];then
	 elif [ $(check_regex "$word" "^[0-9]{2}-[0-9]{2}-[0-9]{2,4}") ];then
		days_before=$(echo $word | sed -r "s/^[0-9]{2}-[0-9]{2}-[0-9]{2,4}\+([0-9])./\+\1/")
	  day=$(echo $word | sed -r "s/^([0-9]{2}).+/\1/")
	  month=$(echo $word | sed -r "s/.+([0-9]{2})-.+/\1/")
	  #year=$(echo $current_word | sed -r "s/.+-([0-9]{2,4}$)/\1/")
	  year=$(echo $word | sed -r "s/.+-([0-9]{2,4})(\+\w{2})?$/\1/")
		
	  taskwarrior+=$(date -d "$year-$month-$day" +"due:%Y-%m-%d")
		due=$(date -d "$year-$month-$day" +"due:%Y-%m-%d")
    remind+="$(LC_ALL=en_US.UTF-8 date -d "$year-$month-$day" +"$days_before %d %b %Y" )"

	fi
done

remind_time="$notification_before_time $hour"
echo taskwarrior: $taskwarrior
echo taskwarrior n: task add $desc $tags $project $depends $due
echo remind: $remind
echo remind n: REM MSG $desc AT $remind_time
