#!/bin/bash
desc=""
tags=""
project=""
due=""
rem_date=""

remind_file="$HOME/.config/nixpkgs/packages/remind/tarefas"

# here we type our task description
task="$@"

#printf "Informe os detalhes da tarefa:"
#read task

check_regex(){
  word=$1
    pattern=$2
  echo $word | grep -E "$pattern"
}

replace(){
 string=$1
 search_string=$2
 replace_by=$3
 echo $string | sed "s/$search_string/$replace_by/"
}

for word in $task; do
    # Palavra normal
    if [ $(check_regex "$word" "^[a-zA-Z]") ];then
        remind+="$word "
        taskwarrior+="$word "
        desc+="$word "

    # Assunto/Categoria
    elif [ $(check_regex "$word" "^\+[a-zA-Z]") ];then
        taskwarrior+="$word "
        current_word=$(replace "$word" "+" "")
        #remind+="$current_word "
        tags+="$word "

    # Projeto
    elif [ $(check_regex "$word" "^@") ];then
        current_word=$(replace "$word" "@" "")
        taskwarrior+="project:$current_word "
        remind+="$current_word "
        project="project:$current_word"
        rem_proj="$current_word"

    # Depends
    elif [ $(check_regex "$word" "^&") ];then
        current_word=$(replace "$word" "&" "")
        taskwarrior+="depends:$current_word "
        depends+="depends:$current_word "


    # Hora
    elif [ $(check_regex "$word" "([0-9]\+)?[0-9]{2}:[0-9]{2}") ];then
        hour=$(echo $word | sed -r "s/([0-9]{2}\+)?([0-9]{2}:[0-9]{2})/\2/")
        notification_before_time=$(echo $word | sed -r "s/([0-9]{2}\+)([0-9]{2}:[0-9]{2})/\1/")
        echo $desc
        [ $notification_before_time = $hour ] && notification_before_time=""
        due="due:$hour"

    # Dias a frente
    elif [ $(check_regex "$word" "^([0-9]+\+)?([0-9])+d?$") ];then
        deadline=$(echo $word | sed -r "s/^(([0-9]+)\+)?([0-9]+)+d$/\3/")
        deadline=$(date -d "$deadline days" +"%Y-%m-%d")
        rem_days_before=$(echo $word| sed -r "s/^(([0-9]+)\+)?([0-9]+)+d$/+\2/")
        [ "$rem_days_before" = "+" ] && unset rem_days_before
        due="due:$deadline"
        rem_date=$(date -d "$deadline" +"%d %b $rem_days_before")

   # Semanas a frente
   elif [ $(check_regex "$word" "^([0-9]+\+)?([0-9])+w?$") ];then
        deadline=$(echo $word | sed -r "s/^(([0-9]+)\+)?([0-9]+)+w$/\3/")
        deadline=$(date -d "$deadline weeks" +"%Y-%m-%d")
        rem_days_before=$(echo $word| sed -r "s/^(([0-9]+)\+)?([0-9]+)+w$/+\2/")
        [ "$rem_days_before" = "+" ] && unset rem_days_before
        due="due:$deadline"
        rem_date=$(date -d "$deadline" +"%d %b $rem_days_before")

   # Meses a frente
   elif [ $(check_regex "$word" "^([0-9]\+)?[0-9]{1,}m(onths)?$") ];then
        deadline=$(echo $word | sed -r "s/^(([0-9]+)\+)?([0-9]+)+m$/\3/")
        deadline=$(date -d "$deadline months" +"%Y-%m-%d")
        rem_days_before=$(echo $word| sed -r "s/^(([0-9]+)\+)?([0-9]+)+m$/+\2/")

        [ "$rem_days_before" = "+" ] && unset rem_days_before
        due="due:$deadline"
        rem_date=$(date -d "$deadline" +"%d %b $rem_days_before")

    # Dia especifico para a tarefa/lembrete
    #elif [ $(check_regex "$current_word" "^[0-9]{2}-[0-9]{2}-[0-9]{2,4}\+?([0-9a-z]{2})?") ];then
    elif [ $(check_regex "$word" "^([0-9]+\+)?([0-9]{2}-[0-9]{2}-[0-9]{2,4})$") ];then
        deadline=$(echo $word | sed -r "s/^([0-9]+\+)?([0-9]{2}-[0-9]{2}-[0-9]{2,4})$/\2/")
        day=$(echo $word | sed -r "s/^([0-9]+\+)?([0-9]{2})-([0-9]{2})-([0-9]{2,4})$/\2/")
        month=$(echo $word | sed -r "s/^([0-9]+\+)?([0-9]{2})-([0-9]{2})-([0-9]{2,4})$/\3/")
        year=$(echo $word | sed -r "s/^([0-9]+\+)?([0-9]{2})-([0-9]{2})-([0-9]{2,4})$/\4/")

        deadline=$(date -d "$year-$month-$day" +"%Y-%m-%d")
        rem_days_before=$(echo $word | sed -r "s/^([0-9]+\+)?([0-9]{2}-[0-9]{2}-[0-9]{2,4})$/\1/")
        [ "$rem_days_before" = "+" ] && unset rem_days_before
        due="due:$deadline"
        rem_date=$(date -d "$deadline" +"%d %b $rem_days_before %Y")
        
        taskwarrior+=$(date -d "$year-$month-$day" +"due:%Y-%m-%d")
        due=$(date -d "$year-$month-$day" +"due:%Y-%m-%d")
        remind+="$(LC_ALL=en_US.UTF-8 date -d "$year-$month-$day" +"$days_before %d %b %Y" )"

    fi
done


# append AT in front of remind time only if we have any text
remind_time="$notification_before_time $hour"
if [ ! "$remind_time" = " " ]; then
     remind_time="AT $remind_time"
fi

#debug
echo taskwarrior: task add $desc $tags $project $depends $due
echo remind: REM $rem_date $days $remind_time MSG $desc $rem_proj

# add task on taskwarrior
task add $desc $tags $project $depends $due
[ $? -ne 0 ] && exit 1

# add reminder in remind
echo REM $rem_date $days $remind_time MSG $desc $rem_proj  >> $remind_file
